/**
 * Daily Preparer Worker
 *
 * Prepares a briefing note for tomorrow. Time-gated to run only
 * between 22:00 and 23:59 local time. Runs every 24 hours.
 */

import * as fs from "fs";
import * as path from "path";
import matter from "gray-matter";
import type { VaultWorker, WorkerContext, WorkerResult } from "../types.js";

const WINDOW_START_HOUR = 22;
const WINDOW_END_HOUR = 24;

export const dailyPreparer: VaultWorker = {
    name: "daily-preparer",
    description: "Prepares tomorrow's briefing note (runs at 10pm)",
    intervalMs: 24 * 60 * 60 * 1000, // 24 hours
    batchSize: 1,

    async run(ctx: WorkerContext): Promise<WorkerResult> {
        const result: WorkerResult = {
            processed: 0,
            created: 0,
            summary: "",
            llmCalls: 0,
            tokensUsed: { input: 0, output: 0 },
        };

        // Time gate: only run between 22:00 and 23:59
        const hour = new Date().getHours();
        if (hour < WINDOW_START_HOUR || hour >= WINDOW_END_HOUR) {
            result.summary = `Outside active window (${WINDOW_START_HOUR}:00-${WINDOW_END_HOUR}:00)`;
            return result;
        }

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        // Read recent memories from last 24hr
        const cutoffMs = Date.now() - 24 * 60 * 60 * 1000;
        const recentMemories: string[] = [];

        const memoriesDir = path.join(ctx.vaultPath, "Notebooks", "Memories");
        if (fs.existsSync(memoriesDir)) {
            const files = fs.readdirSync(memoriesDir)
                .filter(f => f.endsWith(".md"))
                .sort()
                .reverse(); // newest first

            for (const file of files.slice(0, 10)) {
                try {
                    const raw = fs.readFileSync(path.join(memoriesDir, file), "utf-8");
                    const { data, content } = matter(raw);
                    const createdAt = data.createdAt ?? data.updatedAt;
                    if (createdAt && new Date(createdAt).getTime() > cutoffMs) {
                        recentMemories.push(`**${path.basename(file, ".md")}**: ${content.substring(0, 200).replace(/\n/g, " ")}`);
                    }
                } catch { /* skip */ }
            }
        }

        result.processed = recentMemories.length;

        // Count pending jobs
        const pendingJobsDir = path.join(ctx.vaultPath, "_jobs", "pending");
        let pendingJobCount = 0;
        if (fs.existsSync(pendingJobsDir)) {
            pendingJobCount = fs.readdirSync(pendingJobsDir).filter(f => f.endsWith(".md")).length;
        }

        const memoriesSummary = recentMemories.length > 0
            ? recentMemories.join("\n")
            : "No memories recorded today.";

        const prompt = `Here's a summary of what happened today:

## Recent Memories (last 24hr)
${memoriesSummary}

## Pending Jobs
${pendingJobCount} job(s) in the queue

Based on this, prepare a concise briefing for tomorrow:
1. Key accomplishments from today (2-3 bullets)
2. Open threads or things to follow up on
3. Suggested focus for tomorrow morning

Keep it short and actionable — under 300 words.`;

        const systemPrompt = "You are a personal assistant preparing a daily briefing. Be concise and encouraging. Focus on what matters for tomorrow.";

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        const briefing = await ctx.llm(prompt, systemPrompt);
        result.llmCalls++;
        result.tokensUsed.input += prompt.length / 4;
        result.tokensUsed.output += briefing.length / 4;

        // Create note for tomorrow's date
        const tomorrow = new Date();
        tomorrow.setDate(tomorrow.getDate() + 1);
        const tomorrowStr = tomorrow.toISOString().split("T")[0]!;

        const title = `Briefing — ${tomorrowStr}`;
        const content = `> Generated by vault-worker: daily-preparer\n> Prepared at ${new Date().toLocaleTimeString()} based on ${recentMemories.length} memories + ${pendingJobCount} pending jobs\n\n${briefing}`;

        // Ensure Daily Digest folder exists
        const digestDir = path.join(ctx.vaultPath, "Notebooks", "Daily Digest");
        if (!fs.existsSync(digestDir)) {
            fs.mkdirSync(digestDir, { recursive: true });
        }

        await ctx.vault.createNote("Daily Digest", title, content, {
            noteType: "note",
            tags: ["vault-worker", "daily-briefing"],
            source: "vault-worker",
        });

        ctx.audit.append({
            worker: this.name,
            action: "created",
            targetPath: `Notebooks/Daily Digest/${title}.md`,
            details: `Prepared briefing for ${tomorrowStr} from ${recentMemories.length} memories`,
        });

        result.created++;
        result.summary = `Created tomorrow's briefing (${tomorrowStr})`;
        return result;
    },
};
