/**
 * Gap Detector Worker
 *
 * Finds notes < 200 words across Memories/Projects/Insights and
 * suggests missing content. Runs every 6 hours.
 */

import * as fs from "fs";
import * as path from "path";
import matter from "gray-matter";
import type { VaultWorker, WorkerContext, WorkerResult } from "../types.js";

export const gapDetector: VaultWorker = {
    name: "gap-detector",
    description: "Finds thin notes and suggests missing content",
    intervalMs: 6 * 60 * 60 * 1000, // 6 hours
    batchSize: 3,

    async run(ctx: WorkerContext): Promise<WorkerResult> {
        const result: WorkerResult = {
            processed: 0,
            created: 0,
            summary: "",
            llmCalls: 0,
            tokensUsed: { input: 0, output: 0 },
        };

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        // Scan target folders for short notes
        const folders = ["Memories", "Projects", "Insights"];
        const thinNotes: Array<{ title: string; path: string; wordCount: number; excerpt: string }> = [];

        for (const folder of folders) {
            const dir = path.join(ctx.vaultPath, "Notebooks", folder);
            if (!fs.existsSync(dir)) continue;

            const scanDir = (d: string) => {
                for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
                    if (ctx.abortSignal.aborted) return;
                    const fullPath = path.join(d, entry.name);
                    if (entry.isDirectory()) {
                        scanDir(fullPath);
                    } else if (entry.name.endsWith(".md") && entry.name !== "_meta.md") {
                        try {
                            const raw = fs.readFileSync(fullPath, "utf-8");
                            const { content } = matter(raw);
                            const words = content.trim().split(/\s+/).filter(Boolean).length;
                            if (words > 0 && words < 200) {
                                thinNotes.push({
                                    title: path.basename(entry.name, ".md"),
                                    path: path.relative(ctx.vaultPath, fullPath),
                                    wordCount: words,
                                    excerpt: content.substring(0, 300).replace(/\n/g, " "),
                                });
                            }
                        } catch { /* skip */ }
                    }
                }
            };
            scanDir(dir);
        }

        result.processed = thinNotes.length;

        if (thinNotes.length === 0) {
            result.summary = "No thin notes found";
            return result;
        }

        // Pick the thinnest batch
        thinNotes.sort((a, b) => a.wordCount - b.wordCount);
        const batch = thinNotes.slice(0, this.batchSize);

        const notesList = batch
            .map(n => `**${n.title}** (${n.wordCount} words)\n> ${n.excerpt}`)
            .join("\n\n");

        const prompt = `I have the following notes in my knowledge vault that seem incomplete (under 200 words each):

${notesList}

For each note, identify:
1. What key information or context is likely missing
2. What questions remain unanswered
3. One specific suggestion for how to expand it

Be concise and practical. Format as a simple list per note.`;

        const systemPrompt = "You are a knowledge management assistant helping to identify gaps in personal notes. Be specific and actionable. Keep your response under 500 words.";

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        const analysis = await ctx.llm(prompt, systemPrompt);
        result.llmCalls++;
        result.tokensUsed.input += prompt.length / 4;
        result.tokensUsed.output += analysis.length / 4;

        // Create insight note
        const date = new Date().toISOString().split("T")[0]!;
        const title = `Gap Analysis — ${date}`;
        const content = `> Generated by vault-worker: gap-detector\n> Analyzed ${batch.length} thin notes (< 200 words)\n\n## Thin Notes Found\n\n${batch.map(n => `- **[[${n.title}]]** — ${n.wordCount} words`).join("\n")}\n\n## Analysis\n\n${analysis}`;

        await ctx.vault.createNote("Insights", title, content, {
            noteType: "note",
            tags: ["vault-worker", "gap-analysis"],
            source: "vault-worker",
        });

        ctx.audit.append({
            worker: this.name,
            action: "created",
            targetPath: `Notebooks/Insights/${title}.md`,
            details: `Analyzed ${batch.length} thin notes`,
        });

        result.created++;
        result.summary = `Analyzed ${batch.length} thin notes, created gap analysis`;
        return result;
    },
};
