/**
 * Idea Connector Worker
 *
 * Finds highly-similar note pairs (0.75–0.90 cosine similarity) that
 * don't already share wikilinks. Runs every 4 hours.
 */

import type { VaultWorker, WorkerContext, WorkerResult } from "../types.js";

export const ideaConnector: VaultWorker = {
    name: "idea-connector",
    description: "Finds unlinked similar note pairs and explains the conceptual bridge",
    intervalMs: 4 * 60 * 60 * 1000, // 4 hours
    batchSize: 5,

    async run(ctx: WorkerContext): Promise<WorkerResult> {
        const result: WorkerResult = {
            processed: 0,
            created: 0,
            summary: "",
            llmCalls: 0,
            tokensUsed: { input: 0, output: 0 },
        };

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        // Get all embedded note paths
        const embeddedPaths = ctx.search.getEmbeddedNotePaths();
        if (embeddedPaths.length < 4) {
            result.summary = "Not enough embedded notes for comparison";
            return result;
        }

        // Find pairs with high similarity that don't already link
        const LOWER = 0.75;
        const UPPER = 0.95; // Exclude near-duplicates
        const pairs: Array<{ source: string; target: string; score: number }> = [];

        // Sample up to 50 notes to keep it fast
        const sample = embeddedPaths.slice(0, 50);
        for (const notePath of sample) {
            if (ctx.abortSignal.aborted) break;
            const similar = ctx.search.findSimilarNotes(notePath, 5, LOWER);
            const existingLinks = ctx.search.getGraphLinks(notePath).map(l => l.target);

            for (const hit of similar) {
                if (hit.relevance > UPPER) continue; // Too similar = probably same topic
                if (existingLinks.includes(hit.notePath)) continue; // Already linked
                // Avoid duplicates (a→b and b→a)
                const alreadyFound = pairs.some(
                    p => (p.source === hit.notePath && p.target === notePath) ||
                        (p.source === notePath && p.target === hit.notePath),
                );
                if (!alreadyFound) {
                    pairs.push({ source: notePath, target: hit.notePath, score: hit.relevance });
                }
            }
        }

        result.processed = pairs.length;

        if (pairs.length === 0) {
            result.summary = "No unlinked similar pairs found";
            return result;
        }

        // Take the best batch
        pairs.sort((a, b) => b.score - a.score);
        const batch = pairs.slice(0, this.batchSize);

        const pairsList = batch
            .map(p => {
                const sourceTitle = p.source.split("/").pop()?.replace(".md", "") ?? p.source;
                const targetTitle = p.target.split("/").pop()?.replace(".md", "") ?? p.target;
                return `- **${sourceTitle}** ↔ **${targetTitle}** (similarity: ${p.score.toFixed(2)})`;
            })
            .join("\n");

        const prompt = `I have discovered these pairs of notes in my knowledge vault that seem related but aren't explicitly linked yet:

${pairsList}

For each pair, briefly explain:
1. What conceptual bridge connects these two notes
2. One sentence on how understanding the connection could be valuable

Keep it concise — one short paragraph per pair.`;

        const systemPrompt = "You are a knowledge management assistant helping to discover connections between ideas. Be insightful but concise. Keep your total response under 400 words.";

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        const analysis = await ctx.llm(prompt, systemPrompt);
        result.llmCalls++;
        result.tokensUsed.input += prompt.length / 4;
        result.tokensUsed.output += analysis.length / 4;

        // Create connections insight note
        const date = new Date().toISOString().split("T")[0]!;
        const title = `Idea Connections — ${date}`;
        const content = `> Generated by vault-worker: idea-connector\n> Found ${batch.length} unlinked similar note pairs\n\n## Unlinked Connections\n\n${pairsList}\n\n## Analysis\n\n${analysis}`;

        await ctx.vault.createNote("Insights", title, content, {
            noteType: "note",
            tags: ["vault-worker", "connections"],
            source: "vault-worker",
        });

        ctx.audit.append({
            worker: this.name,
            action: "created",
            targetPath: `Notebooks/Insights/${title}.md`,
            details: `Found ${batch.length} unlinked pairs from ${result.processed} candidates`,
        });

        result.created++;
        result.summary = `Found ${batch.length} unlinked similar note pairs, created connections note`;
        return result;
    },
};
