/**
 * Note Enricher Worker
 *
 * Suggests tags and contextual summaries for recent untagged notes.
 * Runs every 8 hours.
 */

import * as path from "path";
import type { VaultWorker, WorkerContext, WorkerResult } from "../types.js";

const RECENT_HOURS = 48;

export const noteEnricher: VaultWorker = {
    name: "note-enricher",
    description: "Suggests tags and context for recent untagged notes",
    intervalMs: 8 * 60 * 60 * 1000, // 8 hours
    batchSize: 5,

    async run(ctx: WorkerContext): Promise<WorkerResult> {
        const result: WorkerResult = {
            processed: 0,
            created: 0,
            summary: "",
            llmCalls: 0,
            tokensUsed: { input: 0, output: 0 },
        };

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        const cutoffMs = Date.now() - RECENT_HOURS * 60 * 60 * 1000;

        // List all notes across all notebooks, filtering for recent + untagged
        const folders = ["Memories", "Projects", "Insights", "Resources"];
        const untaggedNotes: Array<{ title: string; content: string }> = [];

        for (const folder of folders) {
            if (ctx.abortSignal.aborted) break;
            try {
                const notes = await ctx.vault.listNotes(folder);
                for (const note of notes) {
                    const createdAt = (note as any).createdAt;
                    if (!createdAt) continue;
                    const createdMs = new Date(createdAt).getTime();
                    if (createdMs < cutoffMs) continue;

                    const tags: string[] = (note as any).tags ?? [];
                    if (tags.length === 0 || (tags.length === 1 && tags[0] === "vault-worker")) {
                        untaggedNotes.push({
                            title: (note as any).title ?? path.basename(note._filePath ?? "", ".md"),
                            content: note.content?.substring(0, 500) ?? "",
                        });
                    }
                }
            } catch { /* folder may not exist */ }
        }

        result.processed = untaggedNotes.length;

        if (untaggedNotes.length === 0) {
            result.summary = `No untagged notes in the last ${RECENT_HOURS}hr`;
            return result;
        }

        const batch = untaggedNotes.slice(0, this.batchSize);
        const notesList = batch
            .map(n => `**${n.title}**\n> ${n.content.replace(/\n/g, " ")}`)
            .join("\n\n");

        const prompt = `I have the following recently-created notes that have no tags yet:

${notesList}

For each note, provide:
1. 3 suggested tags (lowercase, hyphen-separated, e.g. "machine-learning", "book-notes")
2. One sentence of context/summary

Format as:
## [Note Title]
Tags: tag1, tag2, tag3
Summary: ...`;

        const systemPrompt = "You are a knowledge management assistant. Suggest concise, useful tags based on the content. Tags should be reusable across the vault, not overly specific. Under 400 words total.";

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        const suggestions = await ctx.llm(prompt, systemPrompt);
        result.llmCalls++;
        result.tokensUsed.input += prompt.length / 4;
        result.tokensUsed.output += suggestions.length / 4;

        const date = new Date().toISOString().split("T")[0]!;
        const title = `Enrichment Suggestions — ${date}`;
        const content = `> Generated by vault-worker: note-enricher\n> ${batch.length} untagged note(s) from the last ${RECENT_HOURS}hr\n\n## Notes Reviewed\n\n${batch.map(n => `- **[[${n.title}]]**`).join("\n")}\n\n## Tag & Context Suggestions\n\n${suggestions}`;

        await ctx.vault.createNote("Insights", title, content, {
            noteType: "note",
            tags: ["vault-worker", "enrichment"],
            source: "vault-worker",
        });

        ctx.audit.append({
            worker: this.name,
            action: "created",
            targetPath: `Notebooks/Insights/${title}.md`,
            details: `Enriched ${batch.length} untagged note(s)`,
        });

        result.created++;
        result.summary = `Suggested tags/context for ${batch.length} untagged note(s)`;
        return result;
    },
};
