/**
 * Orphan Rescuer Worker
 *
 * Finds embedded notes with zero graph connections and suggests
 * where they could fit in the vault. Runs every 12 hours.
 */

import type { VaultWorker, WorkerContext, WorkerResult } from "../types.js";

export const orphanRescuer: VaultWorker = {
    name: "orphan-rescuer",
    description: "Finds isolated notes and suggests vault connections",
    intervalMs: 12 * 60 * 60 * 1000, // 12 hours
    batchSize: 5,

    async run(ctx: WorkerContext): Promise<WorkerResult> {
        const result: WorkerResult = {
            processed: 0,
            created: 0,
            summary: "",
            llmCalls: 0,
            tokensUsed: { input: 0, output: 0 },
        };

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        // Get all embedded note paths and find those with no graph links
        const embeddedPaths = ctx.search.getEmbeddedNotePaths();

        if (embeddedPaths.length < 3) {
            result.summary = "Not enough embedded notes to find orphans";
            return result;
        }

        const orphans: Array<{ path: string; title: string }> = [];

        for (const notePath of embeddedPaths) {
            if (ctx.abortSignal.aborted) break;
            // Skip system/log files
            if (notePath.startsWith("_")) continue;

            const links = ctx.search.getGraphLinks(notePath);
            if (links.length === 0) {
                const title = notePath.split("/").pop()?.replace(".md", "") ?? notePath;
                orphans.push({ path: notePath, title });
            }
        }

        result.processed = orphans.length;

        if (orphans.length === 0) {
            result.summary = "No orphaned notes found — great connectivity!";
            return result;
        }

        // Pick random sample from orphans for variety
        const shuffled = orphans.sort(() => Math.random() - 0.5);
        const batch = shuffled.slice(0, this.batchSize);

        // Get a sample of connected notes' titles for context
        const connectedSample = embeddedPaths
            .filter(p => !p.startsWith("_") && ctx.search.getGraphLinks(p).length > 0)
            .slice(0, 20)
            .map(p => p.split("/").pop()?.replace(".md", "") ?? p);

        const orphanList = batch.map(o => `- **${o.title}**`).join("\n");
        const connectedList = connectedSample.slice(0, 10).join(", ");

        const prompt = `I have the following "orphan" notes in my knowledge vault — they have been embedded (processed by AI) but have no connections to other notes:

${orphanList}

Some well-connected notes in the vault for reference:
${connectedList}

For each orphan note, suggest:
1. Which 2-3 existing notes it might connect to (guess based on the title)
2. What topic cluster it might belong to
3. One action to integrate it better (e.g., "Add this to the [[X]] note as a related resource")

Be practical. Under 400 words total.`;

        const systemPrompt = "You are a knowledge management assistant helping connect isolated notes to the broader knowledge graph. Make thoughtful suggestions based on titles alone.";

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        const suggestions = await ctx.llm(prompt, systemPrompt);
        result.llmCalls++;
        result.tokensUsed.input += prompt.length / 4;
        result.tokensUsed.output += suggestions.length / 4;

        const date = new Date().toISOString().split("T")[0]!;
        const title = `Orphan Suggestions — ${date}`;
        const content = `> Generated by vault-worker: orphan-rescuer\n> Found ${orphans.length} orphan(s) of ${embeddedPaths.length} embedded notes (${batch.length} analyzed)\n\n## Orphaned Notes\n\n${orphanList}\n\n## Suggested Connections\n\n${suggestions}`;

        await ctx.vault.createNote("Insights", title, content, {
            noteType: "note",
            tags: ["vault-worker", "orphan-rescue"],
            source: "vault-worker",
        });

        ctx.audit.append({
            worker: this.name,
            action: "created",
            targetPath: `Notebooks/Insights/${title}.md`,
            details: `Analyzed ${batch.length} orphans of ${orphans.length} found`,
        });

        result.created++;
        result.summary = `Found ${orphans.length} orphan note(s), suggested connections for ${batch.length}`;
        return result;
    },
};
