/**
 * Project Nudger Worker
 *
 * Finds projects with no activity in 7+ days and suggests next steps.
 * Runs every 24 hours.
 */

import * as fs from "fs";
import * as path from "path";
import matter from "gray-matter";
import type { VaultWorker, WorkerContext, WorkerResult } from "../types.js";

const STALE_DAYS = 7;

export const projectNudger: VaultWorker = {
    name: "project-nudger",
    description: "Finds stalled projects and suggests next steps",
    intervalMs: 24 * 60 * 60 * 1000, // 24 hours
    batchSize: 3,

    async run(ctx: WorkerContext): Promise<WorkerResult> {
        const result: WorkerResult = {
            processed: 0,
            created: 0,
            summary: "",
            llmCalls: 0,
            tokensUsed: { input: 0, output: 0 },
        };

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        const projectsDir = path.join(ctx.vaultPath, "Notebooks", "Projects");
        if (!fs.existsSync(projectsDir)) {
            result.summary = "No Projects folder found";
            return result;
        }

        const cutoffMs = Date.now() - STALE_DAYS * 24 * 60 * 60 * 1000;
        const staleProjects: Array<{ title: string; lastUpdated: string; excerpt: string }> = [];

        const scanDir = (d: string) => {
            for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
                if (ctx.abortSignal.aborted) return;
                const fullPath = path.join(d, entry.name);
                if (entry.isDirectory()) {
                    scanDir(fullPath);
                } else if (entry.name.endsWith(".md") && entry.name !== "_meta.md") {
                    try {
                        const raw = fs.readFileSync(fullPath, "utf-8");
                        const { data, content } = matter(raw);
                        const updatedAt = data.updatedAt ?? data.createdAt;
                        if (!updatedAt) return;

                        const updatedMs = new Date(updatedAt).getTime();
                        if (updatedMs < cutoffMs) {
                            staleProjects.push({
                                title: path.basename(entry.name, ".md"),
                                lastUpdated: updatedAt,
                                excerpt: content.substring(0, 400).replace(/\n/g, " "),
                            });
                        }
                    } catch { /* skip */ }
                }
            }
        };

        scanDir(projectsDir);
        result.processed = staleProjects.length;

        if (staleProjects.length === 0) {
            result.summary = "No stale projects found";
            return result;
        }

        // Sort by stalest first
        staleProjects.sort((a, b) =>
            new Date(a.lastUpdated).getTime() - new Date(b.lastUpdated).getTime(),
        );
        const batch = staleProjects.slice(0, this.batchSize);

        const projectsList = batch
            .map(p => `**${p.title}** (last updated: ${p.lastUpdated.split("T")[0]})\n> ${p.excerpt}`)
            .join("\n\n");

        const prompt = `I have the following projects in my knowledge vault that haven't been updated in ${STALE_DAYS}+ days:

${projectsList}

For each project:
1. What might be causing the stall? (quick hypothesis)
2. What's the single most concrete next action to get it moving?
3. Is this project worth continuing or should it be archived?

Be direct and practical. Keep it brief — one short paragraph per project.`;

        const systemPrompt = "You are a productive assistant helping someone review stalled projects. Be concise, practical, and gently encouraging. Under 400 words total.";

        if (ctx.abortSignal.aborted) return { ...result, summary: "aborted" };

        const nudge = await ctx.llm(prompt, systemPrompt);
        result.llmCalls++;
        result.tokensUsed.input += prompt.length / 4;
        result.tokensUsed.output += nudge.length / 4;

        const date = new Date().toISOString().split("T")[0]!;
        const title = `Project Nudge — ${date}`;
        const content = `> Generated by vault-worker: project-nudger\n> Found ${batch.length} project(s) with no activity in ${STALE_DAYS}+ days\n\n## Stalled Projects\n\n${batch.map(p => `- **[[${p.title}]]** — last updated ${p.lastUpdated.split("T")[0]}`).join("\n")}\n\n## Next Steps\n\n${nudge}`;

        await ctx.vault.createNote("Insights", title, content, {
            noteType: "note",
            tags: ["vault-worker", "project-review"],
            source: "vault-worker",
        });

        ctx.audit.append({
            worker: this.name,
            action: "created",
            targetPath: `Notebooks/Insights/${title}.md`,
            details: `Nudged ${batch.length} stalled project(s)`,
        });

        result.created++;
        result.summary = `Found ${batch.length} stalled project(s), created nudge note`;
        return result;
    },
};
