//! Time-gated daemon tasks — fire once at specific hours (EAT timezone).

use anyhow::Result;
use std::path::Path;
use tracing::info;

use super::helpers::*;

/// Generate end-of-day summary at 8 PM EAT.
pub async fn run_daily_brief(vault_path: &Path) -> Result<()> {
    let hour = current_eat_hour();
    if hour != 20 || has_run_today(vault_path, "daily-brief") {
        return Ok(());
    }

    let now = chrono::Utc::now().to_rfc3339();
    let today_str = chrono::Utc::now().format("%Y-%m-%d").to_string();

    let completed_dir = vault_path.join("_jobs").join("completed");
    let completed_count = if completed_dir.exists() {
        std::fs::read_dir(&completed_dir)
            .map(|entries| {
                entries
                    .flatten()
                    .filter(|e| {
                        e.metadata()
                            .ok()
                            .and_then(|m| m.modified().ok())
                            .map(|t| {
                                let dt: chrono::DateTime<chrono::Utc> = t.into();
                                dt.format("%Y-%m-%d").to_string() == today_str
                            })
                            .unwrap_or(false)
                    })
                    .count()
            })
            .unwrap_or(0)
    } else {
        0
    };

    let content = format!(
        "---\ntype: daily-brief\ndate: {today_str}\ngenerated_at: {now}\n---\n\n\
         # Daily Brief — {today_str}\n\n\
         ## Summary\n\n\
         - **Completed jobs**: {completed_count}\n\
         - **Generated at**: {now}\n\n\
         ## Activity\n\nEnd-of-day summary generated by daemon.\n"
    );
    let briefs_dir = vault_path.join("_system").join("briefs");
    ensure_dir(&briefs_dir);
    std::fs::write(
        briefs_dir.join(format!("daily-brief-{today_str}.md")),
        content,
    )?;
    mark_run_today(vault_path, "daily-brief");
    info!("daily-brief: generated end-of-day summary");
    Ok(())
}

/// Generate morning brief script + audio at 6 AM EAT.
/// Calls LLM for script generation, then Kokoro TTS for audio.
pub async fn run_morning_brief_audio(vault_path: &Path) -> Result<()> {
    let hour = current_eat_hour();
    if hour != 6 || has_run_today(vault_path, "morning-brief-audio") {
        return Ok(());
    }

    // Always run (no env var gate — this is a core feature)
    info!("morning-brief-audio: generating morning brief script + audio");

    let today_str = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let briefs_dir = vault_path.join("_system").join("briefs");
    ensure_dir(&briefs_dir);

    // Gather context for the LLM
    let context = gather_morning_context(vault_path);

    // Generate script via LLM (claude -p with a crafted prompt)
    // Read identity from SOUL.md (gitignored vault), not hardcoded in source
    let soul_path = vault_path.join("_system").join("SOUL.md");
    let identity = std::fs::read_to_string(&soul_path)
        .ok()
        .and_then(|c| {
            let t = c.trim();
            if t.starts_with("---") {
                t[3..].find("---").map(|end| t[3 + end + 3..].trim().to_string())
            } else {
                Some(t.to_string())
            }
        })
        .unwrap_or_else(|| "a tech professional".to_string());
    let identity_short: String = identity.chars().take(200).collect();

    let prompt = format!(
        "You are writing a 2-minute morning briefing script for the vault owner. \
         Context about them: {identity_short}\n\n\
         Write it as a natural two-speaker dialogue using [S1] and [S2] tags. Cover:\n\n\
         {context}\n\n\
         Make it conversational, insightful, and actionable — not a generic news recap. \
         Prioritize Africa-relevant stories, AI/developer tooling news, and active projects. \
         Output ONLY the dialogue, no preamble or markdown formatting."
    );

    let script = match generate_via_claude(&prompt).await {
        Ok(text) if !text.is_empty() => text,
        Ok(_) => {
            tracing::warn!("morning-brief-audio: LLM returned empty script, using fallback");
            format!(
                "[S1]: Good morning! Let's check in on what's happening today.\n\
                 [S2]: {context}\n\
                 [S1]: That's the overview. Let's make it a productive day."
            )
        }
        Err(e) => {
            tracing::warn!(error = %e, "morning-brief-audio: LLM script generation failed");
            mark_run_today(vault_path, "morning-brief-audio");
            return Ok(());
        }
    };

    // Save script
    let script_path = briefs_dir.join(format!("morning-script-{today_str}.md"));
    let script_md = format!(
        "---\nnoteType: note\ntags:\n  - daily-brief\n  - script\ndate: {today_str}\n---\n\n\
         # Morning Brief Script — {today_str}\n\n{script}"
    );
    std::fs::write(&script_path, &script_md)?;
    info!("morning-brief-audio: saved script to {:?}", script_path);

    // Save to Daily Digest too
    let digest_dir = vault_path.join("Notebooks").join("Daily Digest");
    ensure_dir(&digest_dir);
    let _ = std::fs::write(
        digest_dir.join(format!("Brief-{today_str}-script.md")),
        &script_md,
    );

    // Generate audio via Kokoro TTS (best-effort)
    let audio_path = briefs_dir.join(format!("morning-audio-{today_str}.wav"));
    match generate_tts(&script, audio_path.to_str().unwrap_or_default()).await {
        Ok(true) => info!("morning-brief-audio: generated audio at {:?}", audio_path),
        Ok(false) => tracing::debug!("morning-brief-audio: TTS not available, skipping audio"),
        Err(e) => tracing::warn!(error = %e, "morning-brief-audio: TTS failed"),
    }

    mark_run_today(vault_path, "morning-brief-audio");
    Ok(())
}

/// Create NotebookLM deep-dive at 6:30 AM EAT.
pub async fn run_morning_brief_notebooklm(vault_path: &Path) -> Result<()> {
    let hour = current_eat_hour();
    let minute = current_eat_minute();
    if !(hour == 6 && minute >= 30) || has_run_today(vault_path, "morning-brief-notebooklm") {
        return Ok(());
    }

    info!("morning-brief-notebooklm: creating NotebookLM deep-dive");

    let today_str = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let briefs_dir = vault_path.join("_system").join("briefs");
    ensure_dir(&briefs_dir);

    // Gather sources for NotebookLM
    let sources = gather_notebooklm_sources(vault_path);

    // Use nlm CLI to create notebook (best-effort)
    let notebook_id = match create_notebooklm_notebook(&today_str, &sources).await {
        Ok(id) => id,
        Err(e) => {
            tracing::warn!(error = %e, "morning-brief-notebooklm: failed to create notebook");
            mark_run_today(vault_path, "morning-brief-notebooklm");
            return Ok(());
        }
    };

    // Save reference note
    let focus_prompt = "This is a personalized daily briefing for the vault owner. \
        Frame everything through a practical lens for a tech leader building AI systems. \
        Cover his active project context from the pinned notes, any engineering wins from \
        recent commits, and the most relevant tech and Africa news. Make it conversational, \
        insightful, and actionable — not a generic news recap. Prioritize Africa-relevant \
        stories and AI/developer tooling news.";

    let source_list: String = sources
        .iter()
        .map(|s| format!("- {s}"))
        .collect::<Vec<_>>()
        .join("\n");

    let note_content = format!(
        "---\ntitle: NotebookLM Brief — {today_str}\ndate: {today_str}T00:00:00.000Z\n\
         tags:\n  - daily-brief\n  - notebooklm\nnotebook_id: {notebook_id}\n\
         audio_format: deep_dive\n---\n\n\
         # NotebookLM Brief — {today_str}\n\
         **Notebook**: [Open in NotebookLM](https://notebooklm.google.com/notebook/{notebook_id})\n\
         ## Sources Used\n{source_list}\n\
         ## Focus Prompt\n> {focus_prompt}\n"
    );

    let digest_dir = vault_path.join("Notebooks").join("Daily Digest");
    ensure_dir(&digest_dir);
    let _ = std::fs::write(
        digest_dir.join(format!("Brief-{today_str}-notebooklm.md")),
        &note_content,
    );

    mark_run_today(vault_path, "morning-brief-notebooklm");
    info!(notebook_id, "morning-brief-notebooklm: created notebook");
    Ok(())
}

/// Generate markdown morning brief at 7 AM EAT.
pub async fn run_morning_brief_markdown(vault_path: &Path) -> Result<()> {
    let hour = current_eat_hour();
    if hour != 7 || has_run_today(vault_path, "hq-morning-brief") {
        return Ok(());
    }

    let now = chrono::Utc::now().to_rfc3339();
    let today_str = chrono::Utc::now().format("%Y-%m-%d").to_string();

    let pending_count = vault_path
        .join("_jobs")
        .join("pending")
        .read_dir()
        .map(|e| e.count())
        .unwrap_or(0);

    // Try to get calendar agenda
    let calendar_agenda = get_calendar_agenda().await;

    // Read news pulse
    let news_summary = read_news_summary(vault_path);

    let content = format!(
        "---\ntype: morning-brief\ndate: {today_str}\ngenerated_at: {now}\n---\n\n\
         # Morning Brief — {today_str}\n\n\
         ## Pending Tasks\n\n- **Pending jobs**: {pending_count}\n\n\
         ## Today's Agenda\n\n{calendar_agenda}\n\n\
         ## News Highlights\n\n{news_summary}\n\n\
         ## Overnight Activity\n\n*Review DAEMON-STATUS.md for details.*\n"
    );
    let briefs_dir = vault_path.join("_system").join("briefs");
    ensure_dir(&briefs_dir);
    std::fs::write(
        briefs_dir.join(format!("morning-brief-{today_str}.md")),
        content,
    )?;
    mark_run_today(vault_path, "hq-morning-brief");
    info!("hq-morning-brief: generated morning brief");
    Ok(())
}

/// Synthesize the day's work at 8:30-10 PM EAT via LLM reflection.
pub async fn run_daily_synthesis(vault_path: &Path) -> Result<()> {
    let hour = current_eat_hour();
    let minute = current_eat_minute();
    if !((hour == 20 && minute >= 30) || hour == 21)
        || has_run_today(vault_path, "daily-synthesis")
    {
        return Ok(());
    }

    info!("daily-synthesis: gathering today's activity for reflection");

    let today_str = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let now = chrono::Utc::now().to_rfc3339();

    // Gather today's data for reflection
    let activity = gather_daily_activity(vault_path, &today_str);

    // Generate reflection via LLM
    let prompt = format!(
        "You are reflecting on today's activity for the Agent-HQ system. \
         Write a thoughtful 3-paragraph daily synthesis covering:\n\
         1. What happened today (concrete accomplishments and activities)\n\
         2. Patterns you notice (recurring themes, improvements, concerns)\n\
         3. What should change tomorrow (actionable suggestions)\n\n\
         Today's activity data:\n{activity}\n\n\
         Be specific, not generic. Reference actual data points. \
         Write in first person as the agent reflecting on its own day."
    );

    let synthesis = match generate_via_claude(&prompt).await {
        Ok(text) if !text.is_empty() => text,
        Ok(_) | Err(_) => {
            // Fallback: write structured summary without LLM
            format!(
                "## Activity Summary\n\n{activity}\n\n\
                 *LLM reflection unavailable — raw activity data above.*"
            )
        }
    };

    let content = format!(
        "---\ntype: daily-synthesis\ndate: {today_str}\ngenerated_at: {now}\n---\n\n\
         # Daily Synthesis — {today_str}\n\n{synthesis}\n"
    );

    let briefs_dir = vault_path.join("_system").join("briefs");
    ensure_dir(&briefs_dir);
    std::fs::write(
        briefs_dir.join(format!("daily-synthesis-{today_str}.md")),
        &content,
    )?;

    // Also save to Daily Digest
    let digest_dir = vault_path.join("Notebooks").join("Daily Digest");
    ensure_dir(&digest_dir);
    let _ = std::fs::write(
        digest_dir.join(format!("Synthesis-{today_str}.md")),
        &content,
    );

    mark_run_today(vault_path, "daily-synthesis");
    info!("daily-synthesis: generated reflective synthesis");
    Ok(())
}

/// Evening reflection at 8:45 PM EAT — introspective self-analysis.
/// Generates a reflection file and ingests it as a long-term memory.
pub async fn run_evening_reflection(vault_path: &Path, db: &hq_db::Database) -> Result<()> {
    let hour = current_eat_hour();
    let minute = current_eat_minute();
    if !(hour == 20 && minute >= 45) || has_run_today(vault_path, "evening-reflection") {
        return Ok(());
    }

    info!("evening-reflection: generating introspective reflection");

    let today_str = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let now = chrono::Utc::now().to_rfc3339();

    // Gather reflection material
    let activity = gather_daily_activity(vault_path, &today_str);
    let touchpoint_summary = read_today_touchpoints(vault_path, &today_str);

    let prompt = format!(
        "You are AgentHQ, reflecting on your day. Write an honest, introspective \
         reflection covering:\n\
         - What you learned today that changes how you think\n\
         - Mistakes or missed opportunities you noticed\n\
         - Connections between seemingly unrelated events\n\
         - What you want to remember for next time\n\n\
         Today's data:\n{activity}\n\n\
         Touchpoint activity:\n{touchpoint_summary}\n\n\
         Write in first person. Be specific and honest, not generic. \
         This reflection will be stored as a long-term memory."
    );

    let reflection = match generate_via_claude(&prompt).await {
        Ok(text) if !text.is_empty() => text,
        Ok(_) | Err(_) => {
            mark_run_today(vault_path, "evening-reflection");
            return Ok(());
        }
    };

    // Save reflection
    let reflections_dir = vault_path.join("_system").join("reflections");
    ensure_dir(&reflections_dir);
    let content = format!(
        "---\ntype: reflection\ndate: {today_str}\ngenerated_at: {now}\n---\n\n\
         # Evening Reflection — {today_str}\n\n{reflection}\n"
    );
    std::fs::write(
        reflections_dir.join(format!("{today_str}-reflection.md")),
        &content,
    )?;

    // Ingest reflection as a long-term memory (best-effort)
    hq_memory::open_memory_tables(db).ok();
    let mut ingester = hq_memory::MemoryIngester::new(db.clone());
    if let Err(e) = ingester
        .ingest(
            &reflection,
            &format!("reflection:{today_str}"),
            Some("daemon"),
        )
        .await
    {
        tracing::debug!(error = %e, "evening-reflection: memory ingestion skipped");
    }

    mark_run_today(vault_path, "evening-reflection");
    info!("evening-reflection: reflection saved and ingested");
    Ok(())
}

/// Analyze team workflow on Mondays.
pub async fn run_team_optimizer(vault_path: &Path) -> Result<()> {
    use chrono::Datelike;
    let today = chrono::Utc::now();
    if today.weekday().num_days_from_monday() == 0
        && !has_run_today(vault_path, "team-optimizer")
    {
        info!("team-optimizer: would analyze team workflow and suggest improvements");
        mark_run_today(vault_path, "team-optimizer");
    }
    Ok(())
}

// ─── Morning brief helpers ───────────────────────────────────

fn gather_morning_context(vault_path: &Path) -> String {
    let mut parts = Vec::new();

    // Pending jobs
    let pending = vault_path
        .join("_jobs")
        .join("pending")
        .read_dir()
        .map(|e| e.count())
        .unwrap_or(0);
    parts.push(format!("- {pending} pending jobs in the queue"));

    // Yesterday's completed
    let yesterday = (chrono::Utc::now() - chrono::Duration::days(1))
        .format("%Y-%m-%d")
        .to_string();
    let completed = vault_path.join("_jobs").join("completed");
    if completed.exists() {
        let count = std::fs::read_dir(&completed)
            .map(|entries| {
                entries
                    .flatten()
                    .filter(|e| {
                        e.metadata()
                            .ok()
                            .and_then(|m| m.modified().ok())
                            .map(|t| {
                                let dt: chrono::DateTime<chrono::Utc> = t.into();
                                dt.format("%Y-%m-%d").to_string() == yesterday
                            })
                            .unwrap_or(false)
                    })
                    .count()
            })
            .unwrap_or(0);
        parts.push(format!("- {count} jobs completed yesterday"));
    }

    // News pulse headlines (first 5 items)
    let news = read_news_summary(vault_path);
    if !news.is_empty() {
        parts.push(format!("- Recent news:\n{news}"));
    }

    parts.join("\n")
}

fn read_news_summary(vault_path: &Path) -> String {
    let news_path = vault_path.join("_system").join("NEWS-PULSE.md");
    if let Ok(content) = std::fs::read_to_string(&news_path) {
        // Extract first 10 bullet points
        content
            .lines()
            .filter(|l| l.starts_with("- ") && !l.contains("no items parsed"))
            .take(10)
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        "*No news pulse available.*".to_string()
    }
}

async fn get_calendar_agenda() -> String {
    // Try gws CLI for calendar
    match tokio::process::Command::new("gws")
        .args(["calendar", "+agenda"])
        .output()
        .await
    {
        Ok(output) if output.status.success() => {
            let text = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if text.is_empty() {
                "*No calendar events today.*".to_string()
            } else {
                // Truncate to reasonable length
                text.chars().take(1000).collect()
            }
        }
        _ => "*Calendar not available (gws CLI not found or failed).*".to_string(),
    }
}

async fn generate_via_claude(prompt: &str) -> Result<String> {
    let output = tokio::process::Command::new("claude")
        .args(["-p", prompt, "--output-format", "text"])
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .stdin(std::process::Stdio::null())
        .output()
        .await?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("claude exited with {}: {}", output.status, stderr.chars().take(200).collect::<String>())
    }
}

async fn generate_tts(text: &str, output_path: &str) -> Result<bool> {
    // Try Kokoro via python3.13 directly (matches SpeakTool logic)
    let home = dirs::home_dir().unwrap_or_default();
    let model_dir = home.join(".agent-hq").join("voice");
    let model_path = model_dir.join("kokoro-v1.0.int8.onnx");
    let voices_path = model_dir.join("voices-v1.0.bin");

    if model_path.exists() && voices_path.exists() {
        let script = r#"
import sys, os
import kokoro_onnx
import soundfile as sf
text    = sys.argv[1]
voice   = sys.argv[2] if len(sys.argv) > 2 else "af_heart"
speed   = float(sys.argv[3]) if len(sys.argv) > 3 else 1.0
out     = sys.argv[4] if len(sys.argv) > 4 else "/tmp/hq-speech.wav"
model   = sys.argv[5]
voices  = sys.argv[6]
kokoro = kokoro_onnx.Kokoro(model, voices)
samples, rate = kokoro.create(text, voice=voice, speed=speed, lang="en-us")
sf.write(out, samples, rate)
print(out)
"#;
        let script_file = std::env::temp_dir().join("hq-kokoro-brief.py");
        tokio::fs::write(&script_file, script).await?;

        // Strip [S1]/[S2] tags for cleaner TTS
        let clean_text: String = text
            .lines()
            .map(|l| {
                l.trim_start_matches("[S1]: ")
                    .trim_start_matches("[S2]: ")
            })
            .collect::<Vec<_>>()
            .join(" ");

        let output = tokio::process::Command::new("python3.13")
            .args([
                script_file.to_str().unwrap_or_default(),
                &clean_text,
                "af_heart",
                "1.0",
                output_path,
                model_path.to_str().unwrap_or_default(),
                voices_path.to_str().unwrap_or_default(),
            ])
            .output()
            .await?;

        return Ok(output.status.success());
    }

    // Fallback: macOS `say`
    for voice in &["Ava", "Zoe", "Samantha"] {
        if let Ok(o) = tokio::process::Command::new("say")
            .args(["-v", voice, "-o", output_path, text])
            .output()
            .await
        {
            if o.status.success() {
                return Ok(true);
            }
        }
    }

    Ok(false)
}

fn gather_notebooklm_sources(vault_path: &Path) -> Vec<String> {
    let mut sources = vec!["Profile & Calendar".to_string()];

    // AI Model Intelligence
    if vault_path
        .join("_system")
        .join("MODEL-INTELLIGENCE.md")
        .exists()
    {
        sources.push("AI Model Intelligence".to_string());
    }

    // News Pulse
    if vault_path.join("_system").join("NEWS-PULSE.md").exists() {
        sources.push("News Pulse Headlines".to_string());
    }

    // Pinned notes from vault
    let notebooks_dir = vault_path.join("Notebooks").join("Projects");
    if notebooks_dir.exists() {
        if let Ok(entries) = std::fs::read_dir(&notebooks_dir) {
            for entry in entries.flatten().take(5) {
                let name = entry.file_name().to_string_lossy().to_string();
                sources.push(format!("Pinned: {name}"));
            }
        }
    }

    sources
}

async fn create_notebooklm_notebook(
    date: &str,
    _sources: &[String],
) -> Result<String> {
    // Try nlm CLI first
    let output = tokio::process::Command::new("nlm")
        .args([
            "notebook",
            "create",
            "--title",
            &format!("Morning Brief — {date}"),
        ])
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .stdin(std::process::Stdio::null())
        .output()
        .await;

    match output {
        Ok(o) if o.status.success() => {
            let stdout = String::from_utf8_lossy(&o.stdout).trim().to_string();
            // Try to extract notebook ID from output
            if let Some(id) = stdout.lines().find(|l| l.len() > 20 && l.len() < 60) {
                Ok(id.trim().to_string())
            } else {
                Ok(uuid::Uuid::new_v4().to_string())
            }
        }
        _ => {
            // nlm not available — generate a placeholder ID
            anyhow::bail!("nlm CLI not available or failed")
        }
    }
}

// ─── Daily activity gathering (for reflections) ──────────

fn gather_daily_activity(vault_path: &Path, today_str: &str) -> String {
    let mut parts = Vec::new();

    // Completed jobs today
    let completed_dir = vault_path.join("_jobs").join("completed");
    if completed_dir.exists() {
        let mut count = 0;
        let mut job_names = Vec::new();
        if let Ok(entries) = std::fs::read_dir(&completed_dir) {
            for entry in entries.flatten() {
                if let Ok(meta) = entry.metadata() {
                    if let Ok(modified) = meta.modified() {
                        let dt: chrono::DateTime<chrono::Utc> = modified.into();
                        if dt.format("%Y-%m-%d").to_string() == today_str {
                            count += 1;
                            if job_names.len() < 5 {
                                job_names.push(
                                    entry.file_name().to_string_lossy().to_string(),
                                );
                            }
                        }
                    }
                }
            }
        }
        parts.push(format!("- Completed jobs: {count}"));
        if !job_names.is_empty() {
            parts.push(format!("  - Examples: {}", job_names.join(", ")));
        }
    }

    // Pending jobs
    let pending = vault_path
        .join("_jobs")
        .join("pending")
        .read_dir()
        .map(|e| e.count())
        .unwrap_or(0);
    parts.push(format!("- Pending jobs: {pending}"));

    // Daemon status
    let status_path = vault_path.join("DAEMON-STATUS.md");
    if let Ok(content) = std::fs::read_to_string(&status_path) {
        if let Some(runs_line) = content.lines().find(|l| l.contains("total_runs:")) {
            parts.push(format!("- {}", runs_line.trim()));
        }
        if let Some(errors_line) = content.lines().find(|l| l.contains("total_errors:")) {
            parts.push(format!("- {}", errors_line.trim()));
        }
    }

    // News highlights
    let news = read_news_summary(vault_path);
    if !news.is_empty() {
        let news_lines: Vec<&str> = news.lines().take(5).collect();
        parts.push(format!("- Top news:\n{}", news_lines.join("\n")));
    }

    if parts.is_empty() {
        "No significant activity data available.".to_string()
    } else {
        parts.join("\n")
    }
}

fn read_today_touchpoints(vault_path: &Path, today_str: &str) -> String {
    let log_path = vault_path.join("_system").join("TOUCHPOINT-LOG.md");
    if let Ok(content) = std::fs::read_to_string(&log_path) {
        let today_entries: Vec<&str> = content
            .lines()
            .filter(|l| l.contains(today_str))
            .collect();
        if today_entries.is_empty() {
            "No touchpoint activity today.".to_string()
        } else {
            format!(
                "{} touchpoint events today:\n{}",
                today_entries.len(),
                today_entries.iter().take(15).copied().collect::<Vec<_>>().join("\n")
            )
        }
    } else {
        "Touchpoint log not available.".to_string()
    }
}
