/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ShareRouteImport } from './routes/share'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DrawitRouteImport } from './routes/drawit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultIndexRouteImport } from './routes/vault/index'
import { Route as VaultSplatRouteImport } from './routes/vault/$'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawitRoute = DrawitRouteImport.update({
  id: '/drawit',
  path: '/drawit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const VaultSplatRoute = VaultSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drawit': typeof DrawitRoute
  '/jobs': typeof JobsRoute
  '/plans': typeof PlansRoute
  '/share': typeof ShareRoute
  '/teams': typeof TeamsRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault/$': typeof VaultSplatRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drawit': typeof DrawitRoute
  '/jobs': typeof JobsRoute
  '/plans': typeof PlansRoute
  '/share': typeof ShareRoute
  '/teams': typeof TeamsRoute
  '/vault/$': typeof VaultSplatRoute
  '/vault': typeof VaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drawit': typeof DrawitRoute
  '/jobs': typeof JobsRoute
  '/plans': typeof PlansRoute
  '/share': typeof ShareRoute
  '/teams': typeof TeamsRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault/$': typeof VaultSplatRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drawit'
    | '/jobs'
    | '/plans'
    | '/share'
    | '/teams'
    | '/vault'
    | '/vault/$'
    | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drawit'
    | '/jobs'
    | '/plans'
    | '/share'
    | '/teams'
    | '/vault/$'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/drawit'
    | '/jobs'
    | '/plans'
    | '/share'
    | '/teams'
    | '/vault'
    | '/vault/$'
    | '/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawitRoute: typeof DrawitRoute
  JobsRoute: typeof JobsRoute
  PlansRoute: typeof PlansRoute
  ShareRoute: typeof ShareRoute
  TeamsRoute: typeof TeamsRoute
  VaultRoute: typeof VaultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawit': {
      id: '/drawit'
      path: '/drawit'
      fullPath: '/drawit'
      preLoaderRoute: typeof DrawitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/$': {
      id: '/vault/$'
      path: '/$'
      fullPath: '/vault/$'
      preLoaderRoute: typeof VaultSplatRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface VaultRouteChildren {
  VaultSplatRoute: typeof VaultSplatRoute
  VaultIndexRoute: typeof VaultIndexRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultSplatRoute: VaultSplatRoute,
  VaultIndexRoute: VaultIndexRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawitRoute: DrawitRoute,
  JobsRoute: JobsRoute,
  PlansRoute: PlansRoute,
  ShareRoute: ShareRoute,
  TeamsRoute: TeamsRoute,
  VaultRoute: VaultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
