/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ShareRouteImport } from './routes/share'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultIndexRouteImport } from './routes/vault/index'
import { Route as VaultSplatRouteImport } from './routes/vault/$'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const VaultSplatRoute = VaultSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/share': typeof ShareRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault/$': typeof VaultSplatRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/share': typeof ShareRoute
  '/vault/$': typeof VaultSplatRoute
  '/vault': typeof VaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/share': typeof ShareRoute
  '/vault': typeof VaultRouteWithChildren
  '/vault/$': typeof VaultSplatRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jobs' | '/share' | '/vault' | '/vault/$' | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jobs' | '/share' | '/vault/$' | '/vault'
  id: '__root__' | '/' | '/jobs' | '/share' | '/vault' | '/vault/$' | '/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  ShareRoute: typeof ShareRoute
  VaultRoute: typeof VaultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/$': {
      id: '/vault/$'
      path: '/$'
      fullPath: '/vault/$'
      preLoaderRoute: typeof VaultSplatRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface VaultRouteChildren {
  VaultSplatRoute: typeof VaultSplatRoute
  VaultIndexRoute: typeof VaultIndexRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultSplatRoute: VaultSplatRoute,
  VaultIndexRoute: VaultIndexRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  ShareRoute: ShareRoute,
  VaultRoute: VaultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
